### ISSUE TITLE
kfac optimizer

### ISSUE THREAD

**Issue by RuidongYan666** [gpauloski/llm-pytorch#56] opened 2023-06-28 03:07 UTC
### How did you install the package and dependencies?

```console
Whether the LLM-pytorch supports the  kfac optimizer during the pre-training phase1 or phase 2?
```

### Describe the problem.

Whether the LLM-pytorch supports the  kfac optimizer during the pre-training phase1 or phase 2?

**Comment by gpauloski** [comment] 2023-06-28 05:36
Hi @RuidongYan666, this repository is still being developed so I have not integrated K-FAC with BERT yet. (I'm assuming you are interested in BERT because you mention phase 1/2.) There's an [open issue](https://github.com/gpauloski/llm-pytorch/issues/10) and [milestone for v0.1.0](https://github.com/gpauloski/llm-pytorch/milestone/1) which you can watch to see that status of K-FAC support.

That being said, there's nothing that prevents K-FAC from being used with phase 1 or 2, so you can check out my K-FAC repo (https://github.com/gpauloski/kfac-pytorch) and integrate that into a BERT training script (the one here or another). I have another repo (https://github.com/gpauloski/BERT-PyTorch) which probably has what you are interested in. Jus note that I no longer provide support for that repo so I've archived it, but it was still working okay earlier this year.

I hope this helps! I'll close the issue, but please ask if you have any other questions.

**Closed by gpauloski** 2023-06-28 05:36 UTC
Labels: bug

**Comment by RuidongYan666** [comment] 2023-06-28 05:52
Thankhttps://github.com/gpauloski/BERT-PyTorch)

**Comment by RuidongYan666** [comment] 2023-06-28 06:30
Hi, gpauloski. Thank you for your answer and assistance！

In fact, we are interested in your work and papers. The repo (https://github.com/gpauloski/kfac-pytorch) has indeed been debugged and is able to undergo successful training!

Recently, we focus on the repo (https://github.com/gpauloski/BERT-PyTorch).  Specifically, we use the LAMB for pre-training phase 1 and phase 2, and the code with the default parameter settings runs smoothly. However, when we try to use the kfac optimizer in pre-training phase 2, it has the following error.
     
            "preconditioner = kfac.KFAC(AttributeError: module kfac' has no attribute 'KFAC"

So my question is how to solve this problem?

Best grades.   
Ruidong

**Comment by gpauloski** [comment] 2023-06-29 00:45
That code is for an older version of the `kfac-pytorch` repo. The new import is
```python
from kfac.preconditioner import KFACPreconditioner

preconditioner = KFACPreconditioner(...)
```

There might still be some discrepancies in parameter names so I suggest you check out the updated docstring [here](https://github.com/gpauloski/kfac-pytorch/blob/main/kfac/preconditioner.py#L34-L154).

**Comment by gpauloski** [comment] 2023-06-30 22:56
> However, we only obtain the global_step_999.pt file at the end of phase 1.
> So, my question is what's the save mechanism for checkpoint and why donot we save the global_step_7039.pt?

You can read how the exit conditions are applied within the script [here](https://github.com/gpauloski/BERT-PyTorch/blob/eb22480c0488edc73e329804ff524cc320b144b2/run_pretraining.py#L530-L533).

You'll see there are two parameters that control the number of steps: `max_steps` and `steps`. The former controls the overall number of steps, and the latter controls the number of steps per invocation of the script (for example if you need to break up the training run over multiple batch job submissions). You can see the default values with `--help` or [here](https://github.com/gpauloski/BERT-PyTorch/blob/eb22480c0488edc73e329804ff524cc320b144b2/run_pretraining.py#L126-L129).

> In phase 1, the max_steps=7038 means that the weights of model is updated 7038 times?

Yes, a "step" refers to an update of the model weights. The amount of gradient accumulation is independent of the number of optimization steps. You can see [here](https://github.com/gpauloski/BERT-PyTorch/blob/eb22480c0488edc73e329804ff524cc320b144b2/run_pretraining.py#L213-L228) that gradient accumulation is only a function of the local batch size, global batch size, and world size.

**Comment by RuidongYan666** [comment] 2023-07-18 02:26
Hi, gpauloski.  

We find that using the **previous version of the kfac package** (e.g., kfac-PyTorch-v0.3.2) in Bert-PyTorch pre-training phase 2 can solve the problems we mentioned earlier instead of the latest kfac package (e.g., kfac-pytorch-v0.4.1).   

But we have the following problem during pre-training phase 2 using the KFAC optimizer. More specifically,
when we start training with global_step_7038.pt and kfac-PyTorch-v0.3.2 during phase 2, the initial average_loss is 6.125. 
The loss decreases with the increase of traing step. After 150 steps, the average_loss is 4.2112.  

However, the average_loss increases rapidly after 151-th step such that it is more than 6.5801. 
Finally, at the end of pre-training phase 2, we obtain the pretained Bert model and the average_loss is 7.4134.  
We fine-tune the pretained Bert model for 3 epochs using the SQuAD dataset, the F1 score is 1.9. 

So my question is what causes the loss to invrease? 
（Note that we set the parameters " inv_update_freq=100"  (default=10) and  "factor_update_freq=10" (default=1)）.

Best regards,
Ruidong

**Comment by gpauloski** [comment] 2023-07-19 02:22
Hi, @RuidongYan666.

> So my question is what causes the loss to invrease?

This is a tricky question to answer. Misconfigured hyperparameters, problems in the creation of training batches, numerical instability if you are using half-precision could all be reasons.

Possibly the issue is in the phase 1 training. You report a loss of 6.125 at that start of phase 2. Our training runs started with a loss around 5.5 for phase 2. I'd suggest first performing a training run without K-FAC so you have a baseline for what the loss should be at the start/end of each phase.

If your baseline run without K-FAC does not work either, I have some colleagues that found better results with an older version of BERT-PyTorch. Maybe try checking out commit [`8356d56a0d01b8d34ad7c3f47dcffe748c74c7d9`](https://github.com/gpauloski/BERT-PyTorch/commit/8356d56a0d01b8d34ad7c3f47dcffe748c74c7d9). I can't find the original conversation with my colleagues about this to give you better details, but I think that commit hash is roughly correct.

If you are able to create a small reproducer using the latest version of K-FAC, please open an issue at https://github.com/gpauloski/kfac-pytorch and we can continue discussion there.

Good luck!
